---
swagger: "2.0"
info:
  version: "0.0.0"
  title: "My Persons API"
paths:
  /persons:
    get:
      description: "Gets `Person` objects.\nOptional query param of **size** determines\n\
        size of returned array\n"
      operationId: "personsGET"
      parameters:
      - name: "size"
        in: "query"
        description: "Size of array"
        required: true
        type: "number"
        format: "double"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            title: "ArrayOfPersons"
            items:
              $ref: "#/definitions/Person"
      x-swagger-router-controller: "Default"
definitions:
  Person:
    properties:
      name:
        type: "string"
      status:
        type: "string"
        enum:
        - "alive"
        - "dead"
